#COMMON COSTMAP PARAMETERS

obstacle_range: 2.5 # max range sensor that will put obstacle in costmap (meter)
raytrace_range: 3.0 # max range sensor that will clear space in costmap (meter)

#robot_radius: 0.6 #0.45 # distance a circular robot should be clear of the obstacle
footprint: [[0.6,0],[0.3,-0.5],[-0.3,-0.5],[-0.6,0],[-0.3,0.5],[0.3,0.5]] #[[-0.50,-0.50], [-0.50, 0.50], [0.50, 0.50],[0.50, -0.50]] #[[-0.32,-0.4], [-0.32, 0.4], [0.32, 0.4],[0.32, -0.4]]  # for non-circular robot
inflation_radius: 0.1  # padding for obstacles
cost_scaling_factor: 10 # inversely proportional to the cost of a cell init:5
observation_sources: laser_scan_sensor #  `

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
