#TEB LOCAL PLANNER FOR NAVIGATION

controller_frequency: 40.0 # Hz
planner_frequency: 0.2 # Hz The rate in Hz at which to run the global planning loop. If the frequency is set to 0.0, the global planner will only run when a new goal is received or the local planner reports that its path is blocked.

TebLocalPlannerROS:
  odom_topic: /odom
  map_frame: /map
  # Trajectory
  teb_autosize: True
  dt_ref: 0.4
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: True
  max_global_plan_lookahead_dist: 5.0
  feasibility_check_no_poses: 2
  allow_init_backward_motion: false
  # Robot
  max_vel_x: 0.6
  max_vel_x_backwards: 0.0
  max_vel_theta: 0.8 # the angular velocity is also bounded by min_turning_radius in case of a carlike robot (r = v / omega)
  acc_lim_x: 0.25
  acc_lim_theta: 0.5
  # ***************** Carlike robot parameters ********************
  min_turning_radius: 0.01       # Min turning radius of the carlike robot (compute value using a model or adjust with rqt_reconfigure manually)
  wheelbase: 0.01
  cmd_angle_instead_rotvel: True # stage simulator takes the angle instead of the rotvel as input (twist message)
  footprint_model: # types: "point", " circular", "two_circles", "line","polygon"
    type: "polygon"
    #radius: 0.25 # for type "circular"
    #line_start: [-0.55, 0.0] # for type "line"
    #line_end: [0.0, 0.0] # for type "line"
    #front_offset: 0.32 # for type "two_circles"
    #front_radius: 0.27 # for type "two_circles"
    #rear_offset: -0.25 # for type "two_circles"
    #rear_radius: 0.27 # for type "two_circles"
    #vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19,-0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05],[0.25,0.2] # for type "polygon"
    vertices: [[0.6,0],[0.3,-0.5],[-0.3,-0.5],[-0.6,0],[-0.3,0.5],[0.3,0.5]] # Same as hexagon specified in costmap_common_params and displayed in rviz
  # GoalTolerance
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  free_goal_vel: False
  # Obstacles
  min_obstacle_dist: 0.0 # This value must also include our robot's expansion
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.5
  obstacle_poses_affected: 30
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5
  # Optimization
  no_inner_iterations: 3
  no_outer_iterations: 3
  optimization_activate: True
  optimization_verbose: True
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 100
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_dynamic_obstacle: 10 # not in use yet
  # Homotopy Class Planner
  enable_homotopy_class_planning: False
  enable_multithreading: True
  simple_exploration: False
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 1.0
  selection_alternative_time_cost: False
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False